import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Cormorant_Garamond,
  Montserrat,
  Poppins,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/app/Components/Navbar/Navbar";
import Footer from "@/app/Components/Footer/Footer";
import { GoogleTagManager } from "@next/third-parties/google";
import { UTMProvider } from "./Components/UTMs/UTMs";
import { Suspense } from "react";

const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant_garamond",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleTagManager gtmId="GTM-NZPN2FQX" />

      <body
        className={`${cormorantGaramond.variable} ${montserrat.variable} ${poppins.variable} antialiased`}
      >
        <Suspense fallback={null}>
          <UTMProvider>
            <Navbar />
            {children}
            <Footer />
          </UTMProvider>
        </Suspense>
      </body>
    </html>
  );
}
